--
-- PostgreSQL database dump
--

\restrict yz91RSnRjinxRcsBYAuzWPW0uLiKah0ZFFV3SDGbApmWmIol0twrNC1fiQqdUqs

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY "public"."union_points" DROP CONSTRAINT IF EXISTS "union_points_character_id_fkey";
ALTER TABLE IF EXISTS ONLY "public"."storage" DROP CONSTRAINT IF EXISTS "storage_owner_id_fkey";
ALTER TABLE IF EXISTS ONLY "public"."storage" DROP CONSTRAINT IF EXISTS "storage_item_id_fkey";
ALTER TABLE IF EXISTS ONLY "public"."mail" DROP CONSTRAINT IF EXISTS "mail_sender_id_fkey";
ALTER TABLE IF EXISTS ONLY "public"."mail" DROP CONSTRAINT IF EXISTS "mail_recipient_id_fkey";
ALTER TABLE IF EXISTS ONLY "public"."inventory" DROP CONSTRAINT IF EXISTS "inventory_owner_id_fkey";
ALTER TABLE IF EXISTS ONLY "public"."inventory" DROP CONSTRAINT IF EXISTS "inventory_item_id_fkey";
ALTER TABLE IF EXISTS ONLY "public"."friends" DROP CONSTRAINT IF EXISTS "friends_friend_id_fkey";
ALTER TABLE IF EXISTS ONLY "public"."friends" DROP CONSTRAINT IF EXISTS "friends_character_id_fkey";
ALTER TABLE IF EXISTS ONLY "public"."clan_member" DROP CONSTRAINT IF EXISTS "clan_member_clan_id_fkey";
ALTER TABLE IF EXISTS ONLY "public"."clan_member" DROP CONSTRAINT IF EXISTS "clan_member_character_id_fkey";
DROP INDEX IF EXISTS "public"."character_account_email_index";
ALTER TABLE IF EXISTS ONLY "public"."worldvar" DROP CONSTRAINT IF EXISTS "worldvar_pkey";
ALTER TABLE IF EXISTS ONLY "public"."worldvar" DROP CONSTRAINT IF EXISTS "worldvar_name_key";
ALTER TABLE IF EXISTS ONLY "public"."union_points" DROP CONSTRAINT IF EXISTS "union_points_pkey";
ALTER TABLE IF EXISTS ONLY "public"."storage" DROP CONSTRAINT IF EXISTS "storage_pkey";
ALTER TABLE IF EXISTS ONLY "public"."storage" DROP CONSTRAINT IF EXISTS "storage_owner_id_slot_key";
ALTER TABLE IF EXISTS ONLY "public"."storage" DROP CONSTRAINT IF EXISTS "storage_owner_id_slot_item_id_key";
ALTER TABLE IF EXISTS ONLY "public"."mail" DROP CONSTRAINT IF EXISTS "mail_pkey";
ALTER TABLE IF EXISTS ONLY "public"."item" DROP CONSTRAINT IF EXISTS "item_uuid_key";
ALTER TABLE IF EXISTS ONLY "public"."item" DROP CONSTRAINT IF EXISTS "item_pkey";
ALTER TABLE IF EXISTS ONLY "public"."inventory" DROP CONSTRAINT IF EXISTS "inventory_pkey";
ALTER TABLE IF EXISTS ONLY "public"."inventory" DROP CONSTRAINT IF EXISTS "inventory_owner_id_slot_key";
ALTER TABLE IF EXISTS ONLY "public"."inventory" DROP CONSTRAINT IF EXISTS "inventory_owner_id_slot_item_id_key";
ALTER TABLE IF EXISTS ONLY "public"."friends" DROP CONSTRAINT IF EXISTS "friends_pkey";
ALTER TABLE IF EXISTS ONLY "public"."friends" DROP CONSTRAINT IF EXISTS "friends_character_id_friend_id_key";
ALTER TABLE IF EXISTS ONLY "public"."clan" DROP CONSTRAINT IF EXISTS "clan_pkey";
ALTER TABLE IF EXISTS ONLY "public"."clan" DROP CONSTRAINT IF EXISTS "clan_name_key";
ALTER TABLE IF EXISTS ONLY "public"."clan_member" DROP CONSTRAINT IF EXISTS "clan_member_pkey";
ALTER TABLE IF EXISTS ONLY "public"."character" DROP CONSTRAINT IF EXISTS "character_pkey";
ALTER TABLE IF EXISTS ONLY "public"."character" DROP CONSTRAINT IF EXISTS "character_name_key";
ALTER TABLE IF EXISTS ONLY "public"."account" DROP CONSTRAINT IF EXISTS "account_pkey";
ALTER TABLE IF EXISTS ONLY "public"."account" DROP CONSTRAINT IF EXISTS "account_email_key";
DROP TABLE IF EXISTS "public"."worldvar";
DROP TABLE IF EXISTS "public"."union_points";
DROP TABLE IF EXISTS "public"."storage";
DROP TABLE IF EXISTS "public"."mail";
DROP TABLE IF EXISTS "public"."item";
DROP TABLE IF EXISTS "public"."inventory";
DROP TABLE IF EXISTS "public"."friends";
DROP TABLE IF EXISTS "public"."clan_member";
DROP TABLE IF EXISTS "public"."clan";
DROP TABLE IF EXISTS "public"."character";
DROP TABLE IF EXISTS "public"."account";
--
-- Name: SCHEMA "public"; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA "public" IS 'standard public schema';


SET default_table_access_method = "heap";

--
-- Name: account; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE "public"."account" (
    "id" integer NOT NULL,
    "email" character varying(30) NOT NULL,
    "password" character(64) NOT NULL,
    "salt" character(16) NOT NULL,
    "access_level" integer DEFAULT 0 NOT NULL,
    "remember_token" character varying(100),
    "created" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: account_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE "public"."account" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."account_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: character; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE "public"."character" (
    "id" integer NOT NULL,
    "account_email" character varying(30) NOT NULL,
    "name" character varying(30) NOT NULL,
    "gender_id" smallint DEFAULT 0 NOT NULL,
    "job_id" smallint DEFAULT 0 NOT NULL,
    "face_id" integer DEFAULT 1 NOT NULL,
    "hair_id" integer DEFAULT 1 NOT NULL,
    "level" smallint DEFAULT 1 NOT NULL,
    "exp" integer DEFAULT 0 NOT NULL,
    "hp" integer DEFAULT 50 NOT NULL,
    "mp" integer DEFAULT 40 NOT NULL,
    "stamina" integer DEFAULT 5000 NOT NULL,
    "max_hp" integer DEFAULT 50 NOT NULL,
    "max_mp" integer DEFAULT 40 NOT NULL,
    "max_stamina" integer DEFAULT 5000 NOT NULL,
    "str" smallint DEFAULT 15 NOT NULL,
    "dex" smallint DEFAULT 15 NOT NULL,
    "intt" smallint DEFAULT 15 NOT NULL,
    "con" smallint DEFAULT 15 NOT NULL,
    "cha" smallint DEFAULT 10 NOT NULL,
    "sen" smallint DEFAULT 10 NOT NULL,
    "stat_points" smallint DEFAULT 0 NOT NULL,
    "skill_points" smallint DEFAULT 0 NOT NULL,
    "money" bigint DEFAULT 0 NOT NULL,
    "storage_money" bigint DEFAULT 0 NOT NULL,
    "map_id" smallint DEFAULT 22 NOT NULL,
    "respawn_x" real DEFAULT 577987.99 NOT NULL,
    "respawn_y" real DEFAULT 515579.9805 NOT NULL,
    "town_respawn_id" smallint DEFAULT 22 NOT NULL,
    "town_respawn_x" real DEFAULT 577987.99 NOT NULL,
    "town_respawn_y" real DEFAULT 515579.9805 NOT NULL,
    "union_id" smallint DEFAULT 0 NOT NULL,
    "skills" "jsonb" DEFAULT '[11, 12, 16, 19, 20, 21, 7001]'::"jsonb" NOT NULL,
    "quests" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "hotbar" "jsonb" DEFAULT '[]'::"jsonb" NOT NULL,
    "wishlist" "jsonb" DEFAULT '[]'::"jsonb" NOT NULL,
    "created" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "delete_by" timestamp with time zone,
    CONSTRAINT "character_level_positive" CHECK (("level" > 0)),
    CONSTRAINT "character_money_positive" CHECK (("money" >= 0)),
    CONSTRAINT "character_storage_money_positive" CHECK (("storage_money" >= 0))
);


--
-- Name: character_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE "public"."character" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."character_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clan; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE "public"."clan" (
    "id" integer NOT NULL,
    "name" character varying(30) NOT NULL,
    "description" character varying(255),
    "motd" character varying(1024),
    "level" smallint DEFAULT 1 NOT NULL,
    "points" bigint DEFAULT 0 NOT NULL,
    "money" bigint DEFAULT 0 NOT NULL,
    "marker_front" smallint DEFAULT 0 NOT NULL,
    "marker_back" smallint DEFAULT 0 NOT NULL,
    "marker_crc" smallint,
    "created" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: clan_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE "public"."clan" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."clan_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clan_member; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE "public"."clan_member" (
    "id" integer NOT NULL,
    "character_id" integer NOT NULL,
    "clan_id" integer NOT NULL,
    "rank" smallint DEFAULT 1 NOT NULL,
    "points" bigint DEFAULT 0 NOT NULL,
    "joined" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: clan_member_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE "public"."clan_member" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."clan_member_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: friends; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE "public"."friends" (
    "id" integer NOT NULL,
    "character_id" integer NOT NULL,
    "friend_id" integer NOT NULL
);


--
-- Name: friends_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE "public"."friends" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."friends_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE "public"."inventory" (
    "id" integer NOT NULL,
    "owner_id" integer NOT NULL,
    "item_id" integer NOT NULL,
    "slot" smallint NOT NULL,
    "quantity" smallint DEFAULT 1 NOT NULL,
    CONSTRAINT "inventory_quantity_positive" CHECK (("quantity" >= 0)),
    CONSTRAINT "inventory_slot_positive" CHECK (("slot" >= 0))
);


--
-- Name: inventory_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE "public"."inventory" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."inventory_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: item; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE "public"."item" (
    "id" integer NOT NULL,
    "uuid" "uuid" NOT NULL,
    "game_data_id" integer DEFAULT 0 NOT NULL,
    "type_id" integer DEFAULT 0 NOT NULL,
    "stat_id" integer DEFAULT 0 NOT NULL,
    "grade" integer DEFAULT 0 NOT NULL,
    "durability" integer DEFAULT 10 NOT NULL,
    "lifespan" integer DEFAULT 1000 NOT NULL,
    "appraisal" boolean DEFAULT false NOT NULL,
    "socket" boolean DEFAULT false NOT NULL,
    "crafted" boolean DEFAULT false NOT NULL,
    CONSTRAINT "grade_positive" CHECK (("grade" >= 0))
);


--
-- Name: item_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE "public"."item" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."item_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mail; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE "public"."mail" (
    "id" integer NOT NULL,
    "sent" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "sender_id" integer NOT NULL,
    "recipient_id" integer NOT NULL,
    "message" character varying(255) NOT NULL
);


--
-- Name: mail_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE "public"."mail" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."mail_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: storage; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE "public"."storage" (
    "id" integer NOT NULL,
    "owner_id" integer NOT NULL,
    "item_id" integer NOT NULL,
    "slot" smallint NOT NULL,
    "quantity" smallint DEFAULT 1 NOT NULL,
    CONSTRAINT "storage_quantity_positive" CHECK (("quantity" >= 0)),
    CONSTRAINT "storage_slot_positive" CHECK (("slot" >= 0))
);


--
-- Name: storage_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE "public"."storage" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."storage_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: union_points; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE "public"."union_points" (
    "id" integer NOT NULL,
    "character_id" integer NOT NULL,
    "union1" integer DEFAULT 0 NOT NULL,
    "union2" integer DEFAULT 0 NOT NULL,
    "union3" integer DEFAULT 0 NOT NULL,
    "union4" integer DEFAULT 0 NOT NULL,
    "union5" integer DEFAULT 0 NOT NULL,
    "union6" integer DEFAULT 0 NOT NULL,
    "union7" integer DEFAULT 0 NOT NULL,
    "union8" integer DEFAULT 0 NOT NULL,
    "union9" integer DEFAULT 0 NOT NULL,
    "union10" integer DEFAULT 0 NOT NULL
);


--
-- Name: union_points_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE "public"."union_points" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."union_points_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: worldvar; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE "public"."worldvar" (
    "id" integer NOT NULL,
    "name" character varying(50) NOT NULL,
    "data" "jsonb" NOT NULL,
    "modified" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: worldvar_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE "public"."worldvar" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."worldvar_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: account account_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."account"
    ADD CONSTRAINT "account_email_key" UNIQUE ("email");


--
-- Name: account account_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."account"
    ADD CONSTRAINT "account_pkey" PRIMARY KEY ("id");


--
-- Name: character character_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."character"
    ADD CONSTRAINT "character_name_key" UNIQUE ("name");


--
-- Name: character character_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."character"
    ADD CONSTRAINT "character_pkey" PRIMARY KEY ("id");


--
-- Name: clan_member clan_member_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."clan_member"
    ADD CONSTRAINT "clan_member_pkey" PRIMARY KEY ("id");


--
-- Name: clan clan_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."clan"
    ADD CONSTRAINT "clan_name_key" UNIQUE ("name");


--
-- Name: clan clan_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."clan"
    ADD CONSTRAINT "clan_pkey" PRIMARY KEY ("id");


--
-- Name: friends friends_character_id_friend_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."friends"
    ADD CONSTRAINT "friends_character_id_friend_id_key" UNIQUE ("character_id", "friend_id");


--
-- Name: friends friends_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."friends"
    ADD CONSTRAINT "friends_pkey" PRIMARY KEY ("id");


--
-- Name: inventory inventory_owner_id_slot_item_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."inventory"
    ADD CONSTRAINT "inventory_owner_id_slot_item_id_key" UNIQUE ("owner_id", "slot", "item_id");


--
-- Name: inventory inventory_owner_id_slot_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."inventory"
    ADD CONSTRAINT "inventory_owner_id_slot_key" UNIQUE ("owner_id", "slot");


--
-- Name: inventory inventory_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."inventory"
    ADD CONSTRAINT "inventory_pkey" PRIMARY KEY ("id");


--
-- Name: item item_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."item"
    ADD CONSTRAINT "item_pkey" PRIMARY KEY ("id");


--
-- Name: item item_uuid_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."item"
    ADD CONSTRAINT "item_uuid_key" UNIQUE ("uuid");


--
-- Name: mail mail_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."mail"
    ADD CONSTRAINT "mail_pkey" PRIMARY KEY ("id");


--
-- Name: storage storage_owner_id_slot_item_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."storage"
    ADD CONSTRAINT "storage_owner_id_slot_item_id_key" UNIQUE ("owner_id", "slot", "item_id");


--
-- Name: storage storage_owner_id_slot_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."storage"
    ADD CONSTRAINT "storage_owner_id_slot_key" UNIQUE ("owner_id", "slot");


--
-- Name: storage storage_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."storage"
    ADD CONSTRAINT "storage_pkey" PRIMARY KEY ("id");


--
-- Name: union_points union_points_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."union_points"
    ADD CONSTRAINT "union_points_pkey" PRIMARY KEY ("id");


--
-- Name: worldvar worldvar_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."worldvar"
    ADD CONSTRAINT "worldvar_name_key" UNIQUE ("name");


--
-- Name: worldvar worldvar_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."worldvar"
    ADD CONSTRAINT "worldvar_pkey" PRIMARY KEY ("id");


--
-- Name: character_account_email_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "character_account_email_index" ON "public"."character" USING "btree" ("account_email");


--
-- Name: clan_member clan_member_character_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."clan_member"
    ADD CONSTRAINT "clan_member_character_id_fkey" FOREIGN KEY ("character_id") REFERENCES "public"."character"("id") ON DELETE CASCADE;


--
-- Name: clan_member clan_member_clan_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."clan_member"
    ADD CONSTRAINT "clan_member_clan_id_fkey" FOREIGN KEY ("clan_id") REFERENCES "public"."clan"("id") ON DELETE CASCADE;


--
-- Name: friends friends_character_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."friends"
    ADD CONSTRAINT "friends_character_id_fkey" FOREIGN KEY ("character_id") REFERENCES "public"."character"("id") ON DELETE CASCADE;


--
-- Name: friends friends_friend_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."friends"
    ADD CONSTRAINT "friends_friend_id_fkey" FOREIGN KEY ("friend_id") REFERENCES "public"."character"("id") ON DELETE CASCADE;


--
-- Name: inventory inventory_item_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."inventory"
    ADD CONSTRAINT "inventory_item_id_fkey" FOREIGN KEY ("item_id") REFERENCES "public"."item"("id") ON DELETE CASCADE;


--
-- Name: inventory inventory_owner_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."inventory"
    ADD CONSTRAINT "inventory_owner_id_fkey" FOREIGN KEY ("owner_id") REFERENCES "public"."character"("id") ON DELETE CASCADE;


--
-- Name: mail mail_recipient_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."mail"
    ADD CONSTRAINT "mail_recipient_id_fkey" FOREIGN KEY ("recipient_id") REFERENCES "public"."character"("id") ON DELETE CASCADE;


--
-- Name: mail mail_sender_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."mail"
    ADD CONSTRAINT "mail_sender_id_fkey" FOREIGN KEY ("sender_id") REFERENCES "public"."character"("id") ON DELETE CASCADE;


--
-- Name: storage storage_item_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."storage"
    ADD CONSTRAINT "storage_item_id_fkey" FOREIGN KEY ("item_id") REFERENCES "public"."item"("id") ON DELETE CASCADE;


--
-- Name: storage storage_owner_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."storage"
    ADD CONSTRAINT "storage_owner_id_fkey" FOREIGN KEY ("owner_id") REFERENCES "public"."character"("id") ON DELETE CASCADE;


--
-- Name: union_points union_points_character_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."union_points"
    ADD CONSTRAINT "union_points_character_id_fkey" FOREIGN KEY ("character_id") REFERENCES "public"."character"("id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict yz91RSnRjinxRcsBYAuzWPW0uLiKah0ZFFV3SDGbApmWmIol0twrNC1fiQqdUqs

